name: Build

on:
  workflow_call:
    secrets:
      PAT:
        required: true

env:
  CARGO_TERM_COLOR: always

#control branch manual action limitation https://stackoverflow.com/questions/74633548/how-to-allow-manual-workflow-dispatch-only-on-specific-branches
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set github url and credentials
      run: |
        /usr/bin/git config --global --add url."https://${{ secrets.PAT }}:x-oauth-basic@github".insteadOf ssh://git@github
        /usr/bin/git config --global --add url."https://${{ secrets.PAT }}:x-oauth-basic@github".insteadOf https://github
        /usr/bin/git config --global --add url."https://${{ secrets.PAT }}:x-oauth-basic@github".insteadOf git@github
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose